name: instagramclon
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  simple_animations: ^4.0.1
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.0
  badges: ^2.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  fluttertoast: ^8.0.9
  device_info_plus: ^3.2.2
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  share_plus: ^3.1.0
  http: ^0.13.4
  get: ^4.6.1
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/billabong.ttf

